// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneFiberService.Model
{
    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal? Phone { get; set; }
        public decimal? Salary { get; set; }
        public string Department { get; set; }
    }
}